# name: Run Azure Login with OpenID Connect
# on: [push]
# workflow_dispatch:
# permissions:
#       id-token: write
#       contents: read   

name: Run Azure Login with SP

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          #enable-AzPSSession: true
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 

    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup -Name "Default"
        azPSVersion: "latest"

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az storage -h